version: 2.1
executors:
  packer:
    docker:
      - image: wesleycharlesblake/devops-tools:0.1.20
    working_directory: ~/parity-eth-project/packer

  terraform:
    docker:
      - image: hashicorp/terraform:0.12.20
    working_directory: ~/parity-eth-project/terraform

orbs:
  compare-url: iynere/compare-url@1.2.0

jobs:

  packer-validate:
    executor: packer
    steps:
      - checkout:
          path: ~/parity-eth-project
      - run:
          name: Validate base
          command: packer validate parity-eth.json

  packer-build: &packer-build
    executor: packer
    steps:
      - checkout:
          path: ~/parity-eth-project

      - compare-url/use:
          step-name: Build base
          attach-workspace: true
          custom-logic: |

            SUB_DIR=packer

            if [[ $(git diff $COMMIT_RANGE --name-status | grep "$SUB_DIR") ]]; then

              echo "files changed in  ${SUB_DIR}/ ; building new AMI"

              packer build parity-eth.json

            else
              echo "${SUB_DIR}/ not modified; no need to publish"
            fi

  tf-validate: &tf-validate
    executor: terraform
    steps:
      - checkout:
          path: ~/parity-eth-project
      - run:
          name: Terraform Validate
          command: |
            printf 'credentials "app.terraform.io" { \n  token = "%s" \n}\n' "$TFE_TOKEN" > ~/.terraformrc

            cd ${ENV}
            terraform init
            terraform validate
          no_output_timeout: 30m

  tf-plan: &tf-plan
    executor: terraform
    steps:
      - checkout:
          path: ~/parity-eth-project
      - run:
          name: Terraform Plan
          command: |
            printf 'credentials "app.terraform.io" { \n  token = "%s" \n}\n' "$TFE_TOKEN" > ~/.terraformrc

            cd ${ENV}
            terraform init
            terraform plan
          no_output_timeout: 30m

  packer-build-prod:
    <<: *packer-build
  packer-build-qa:
    <<: *packer-build
  tf-validate-prod:
    <<: *tf-validate
  tf-validate-qa:
    <<: *tf-validate
  tf-plan-prod:
    <<: *tf-plan
  tf-plan-qa:
    <<: *tf-plan

workflows:
  version: 2
  build-and-deploy:
    jobs:
      ### Common to all ENVs
      - packer-validate
      - compare-url/reconstruct:
          context: CIRCLECI-API

      ### QA
      - packer-build-qa:
          context: AWS-DEVOPS
          requires:
            - packer-validate
            - compare-url/reconstruct
          filters:
            branches:
              ignore: master
      - tf-validate-qa:
          context: AWS-DEVOPS
          filters:
            branches:
              ignore: master
      - tf-plan-qa:
          context: AWS-DEVOPS
          requires:
            - packer-build-qa
          filters:
            branches:
              ignore: master

      ### PROD
      - packer-build-prod:
          context: AWS-PROD
          requires:
            - packer-validate
            - compare-url/reconstruct
          filters:
            branches:
              only: master
      - tf-validate-prod:
          context: AWS-PROD
          filters:
            branches:
              only: master
      - tf-plan-prod:
          context: AWS-PROD
          requires:
            - packer-build-prod
          filters:
            branches:
              only: master